### ISSUE TITLE
It is kinda uncomfortable queueing for casual

### ISSUE THREAD

**Issue by Pleasurewithoutresponsibility** [p3tr1ch0r/insomniaHUD#27]
I play a lot of casual mode and the issue i have with this hud that is not program-wise but still kinda uncomfortable is, that
the "play game" button is at upper right corner, and I have to move the cursor all the way down to the bottom to choose the mode, and then to the right again to start search.
Also, with some huds I can press a button to skip the welcome message.. (Usually E or C) so please consider adding that too..?
This is just a minor inconvenience and just a suggestion and the hud is very cool otherwise.

**Comment by p3tr1ch0r** [comment]
> I play a lot of casual mode and the issue i have with this hud that is not program-wise but still kinda uncomfortable is, that
the "play game" button is at upper right corner, and I have to move the cursor all the way down to the bottom to choose the mode, and then to the right again to start search.

Improved in 68530ca8b60bcb2fe2a533498d34b656d93713f7.

> Also, with some huds I can press a button to skip the welcome message.. (Usually E or C) so please consider adding that too..?
This is just a minor inconvenience and just a suggestion and the hud is very cool otherwise.

You can use A and D to move between pages.
